stages:
  - Build
  - Collect

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_JOB_NAME_SLUG-$CI_JOB_ID

# Unit01
Unit01_Build:
  extends: .build
  variables:
    PROJECT_PATH: "Enclustra/bu-sp/mercury/mercury_xu9/mercury_xu9_reference_design/Mercury_XU9_PE1_Reference_Design"
    BASEBOARD: "PE1"
    MACHINE: "refdes-xu9-pe1"
  parallel:
    matrix:
      - PRODUCTMODEL: ["ME-XU9-7EV-2I-D12E-L11"]
        BOOTMODE: ["sd", "emmc"]

Unit01_Collect:
  extends: .collect
  needs:
    - Unit01_Build

# Unit02: TODO

# Unit03
Unit03_Build:
  extends: .build
  variables:
    PROJECT_PATH: "Enclustra/bu-sp/mercury/mercury_xu61/mercury_xu61_reference_design/Mercury_XU61_ST1_Reference_Design"
    BASEBOARD: "ST1"
    MACHINE: "refdes-xu61-st1"
  parallel:
    matrix:
      - PRODUCTMODEL: ["ME-XU61-2CG-L1I4524-D9-NU"]
        BOOTMODE: ["sd", "emmc"]

Unit03_Collect:
  extends: .collect
  needs:
    - Unit03_Build

# Unit04
Unit04_Build:
  extends: .build
  variables:
    PROJECT_PATH: "Enclustra/bu-sp/mercury/mercury_xu7/mercury_xu7_reference_design/Mercury_XU7_PE3_Reference_Design"
    BASEBOARD: "PE3"
    MACHINE: "refdes-xu7-pe3"
  parallel:
    matrix:
      - PRODUCTMODEL: ["ME-XU7-15EG-2I-D12E"]
        BOOTMODE: ["sd", "emmc"]

Unit04_Collect:
  extends: .collect
  needs:
    - Unit04_Build

# Unit05
Unit05_Build:
  extends: .build
  variables:
    PROJECT_PATH: "Enclustra/bu-sp/mercury/mercury_xu1/mercury_xu1_reference_design/Mercury_XU1_PE1_Reference_Design"
    BASEBOARD: "PE1"
    MACHINE: "refdes-xu1-pe1"
  parallel:
    matrix:
      - PRODUCTMODEL: ["ME-XU1-15EG-2I-D12E"]
        BOOTMODE: ["sd", "emmc"]

Unit05_Collect:
  extends: .collect
  needs:
    - Unit05_Build

# Unit06
Unit06_Build:
  extends: .build
  variables:
    PROJECT_PATH: "Enclustra/bu-sp/mars/mars_xu3/mars_xu3_reference_design/Mars_XU3_ST3_Reference_Design"
    BASEBOARD: "ST3"
    MACHINE: "refdes-xu3-st3"
  parallel:
    matrix:
      - PRODUCTMODEL: ["MA-XU3-3EG-2I-D11"]
        BOOTMODE: ["sd", "emmc"]

Unit06_Collect:
  extends: .collect
  needs:
    - Unit06_Build

# Unit07: TODO

# Unit08
Unit08_Build:
  extends: .build
  variables:
    PROJECT_PATH: "Enclustra/bu-sp/mercury/mercury_xu8/mercury_xu8_reference_design/Mercury_XU8_PE3_Reference_Design"
    BASEBOARD: "PE3"
    MACHINE: "refdes-xu8-pe3"
  parallel:
    matrix:
      - PRODUCTMODEL: ["ME-XU8-7EV-2I-D12E"]
        BOOTMODE: ["sd", "emmc"]

Unit08_Collect:
  extends: .collect
  needs:
    - Unit08_Build