include:
  local: .gitlab-ci-templates.yml

workflow:
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /release/
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never

stages:
  - generate
  - trigger

variables:
  TOOL_VERSION: "2024.2"

generate-build-all-config:
  extends: .generate
  script:
    - !reference [.generate, script]
    - PYTHONPATH=$(pwd) python3 Yocto/YoctoGen.py --output_path=../../ --tool_version=${TOOL_VERSION} --generate_build
    - cd ../../ && cat generated-build-all-config.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE == "weekly"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
  artifacts:
    paths:
      - generated-build-all-config.yml

generate-nightly-config:
  extends: .generate
  script:
    - !reference [.generate, script]
    - PYTHONPATH=$(pwd) python3 Yocto/YoctoGen.py --output_path=../../ --tool_version=${TOOL_VERSION} --generate_nightly
    - cd ../../ && cat generated-nightly-config.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE == "nightly"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
  artifacts:
    paths:
      - generated-nightly-config.yml

generate-release-config:
  extends: 
    - .release_rules
    - .generate
  script:
    - !reference [.generate, script]
    - PYTHONPATH=$(pwd) python3 Yocto/YoctoGen.py --output_path=../../ --tool_version=${TOOL_VERSION} --generate_release
    - cd ../../ && cat generated-*.yml
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  artifacts:
    paths:
      - generated-lab-release-config.yml
      - generated-build-all-release-config.yml

build-pipeline:
  when: manual
  stage: trigger
  trigger:
    strategy: depend
    include:
      - artifact: generated-build-all-config.yml
        job: generate-build-all-config
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE == "nightly"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE == "weekly"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"

nightly-pipeline:
  stage: trigger
  trigger:
    strategy: depend
    include:
      - artifact: generated-nightly-config.yml
        job: generate-nightly-config
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE == "weekly"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE == "nightly"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"

release-lab-pipeline:
  extends: .release_rules
  when: manual
  stage: trigger
  trigger:
    strategy: depend
    include:
      - artifact: generated-lab-release-config.yml
        job: generate-release-config
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG

release-build-all-pipeline:
  extends: .release_rules
  when: manual
  stage: trigger
  trigger:
    strategy: depend
    include:
      - artifact: generated-build-all-release-config.yml
        job: generate-release-config
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG
