#@TYPE: Machine
#@NAME: refdes-xu5er-pe1
#@DESCRIPTION: Machine configuration for the refdes-xu5er-pe1 boards.

#### Preamble
MACHINEOVERRIDES =. "${@['', 'refdes-xu5er-pe1:']['refdes-xu5er-pe1' !='${MACHINE}']}"

# Required generic machine inclusion
require conf/machine/xu5er-module.conf
require pe1-generic.conf

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', 'refdes_xu5er_pe1']['refdes-xu5er-pe1' != '${MACHINE}']}"
