## preamble
MACHINEOVERRIDES =. "${@['', 'xu6cg-module:']['xu6cg-module' != '${MACHINE}']}"

## based on
require conf/machine/zynqmp-generic.conf

## regular settings
PMU_FIRMWARE_IMAGE_NAME = "pmu-firmware-zynqmp"

## additional packages
IMAGE_INSTALL:pn-petalinux-image-minimal:append = " libgpiod libgpiod-dev libgpiod-tools"

## postabmle
PACKAGE_EXTRA_ARCHS:append = "${@['', ' xu6cg_module']['xu6cg-module' != "${MACHINE}"]}"
