## preamble
MACHINEOVERRIDES =. "${@['', 'xu7-module:']['xu7-module' != '${MACHINE}']}"

## FIXME: This is a workaxound to allow the use of the same machine configuration for different machine types.
# In future version of Petalinux, this probably will be replaced.
CONDITIONAL_REQUIRE = "${@'conf/machine/zynqmp-ev-generic.conf' if 'ev' in d.getVar('MACHINE') else \
'conf/machine/zynqmp-eg-generic.conf' if 'eg' in d.getVar('MACHINE') else \
'conf/machine/zynqmp-cg-generic.conf' if 'cg' in d.getVar('MACHINE') else \
'conf/machine/zynqmp-generic.conf'}"
require ${CONDITIONAL_REQUIRE}

## regular settings
PMU_FIRMWARE_IMAGE_NAME = "pmu-firmware-zynqmp"

## postabmle
PACKAGE_EXTRA_ARCHS:append = "${@['', ' xu7_module']['xu7-module' != "${MACHINE}"]}"
