## preamble
MACHINEOVERRIDES =. "${@['', 'xu9-module:']['xu9-module' != '${MACHINE}']}"

## based on
require conf/machine/zynqmp-generic.conf

## regular settings
PMU_FIRMWARE_IMAGE_NAME = "pmu-firmware-zynqmp"

## postabmle
PACKAGE_EXTRA_ARCHS:append = "${@['', ' xu9_module']['xu9-module' != "${MACHINE}"]}"
