BBPATH .= ":${LAYERDIR}"

BBFILES += " \
${LAYERDIR}/recipes-*/*/*.bb \
${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "enclustra-baseboard"
BBFILE_PATTERN_enclustra-baseboard = "^${LAYERDIR}/"
BBFILE_PRIORITY_enclustra-baseboard = "20"
LAYERVERSION = "1"
LAYERSERIES_COMPAT_enclustra-baseboard = "scarthgap"
