#@TYPE: Machine
#@NAME: refdes-zx3-eb1
#@DESCRIPTION: Machine configuration for the refdes-zx3-eb1 boards.

#### Preamble
MACHINEOVERRIDES =. "${@['', 'refdes-zx3-eb1:']['refdes-zx3-eb1' !='${MACHINE}']}"

# Required generic machine inclusion
require conf/machine/zx3-module.conf
require eb1-generic.conf

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', 'refdes_zx3_eb1']['refdes-zx3-eb1' != '${MACHINE}']}"
