## preamble
MACHINEOVERRIDES =. "${@['', 'xru30-module:']['xru30-module' != '${MACHINE}']}"

require conf/machine/zynqmp-override.inc
require conf/machine/qspi-64-mbytes.inc

## postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' xru30_module']['xru30-module' != "${MACHINE}"]}"
