## preamble
MACHINEOVERRIDES =. "${@['', 'xu3-module:']['xu3-module' != '${MACHINE}']}"

require conf/machine/zynqmp-override.inc
require conf/machine/qspi-64-mbytes.inc

## postabmle
PACKAGE_EXTRA_ARCHS:append = "${@['', ' xu3_module']['xu3-module' != "${MACHINE}"]}"
