## preamble
MACHINEOVERRIDES =. "${@['', 'xu9-module:']['xu9-module' != '${MACHINE}']}"

require conf/machine/zynqmp-override.inc

## postabmle
PACKAGE_EXTRA_ARCHS:append = "${@['', ' xu9_module']['xu9-module' != "${MACHINE}"]}"
