MACHINEOVERRIDES =. "${@['', 'zx1-module:']['zx1-module' != '${MACHINE}']}"

require conf/machine/zynq-override.inc
require conf/machine/qspi-64-mbytes.inc

PACKAGE_EXTRA_ARCHS:append = "${@['', ' zx1_module']['zx1-module' != "${MACHINE}"]}"
