MACHINEOVERRIDES =. "${@['', 'zx2-module:']['zx2-module' != '${MACHINE}']}"

require conf/machine/zynq-generic.conf

PACKAGE_EXTRA_ARCHS:append = "${@['', ' zx2_module']['zx2-module' != "${MACHINE}"]}"
