MACHINEOVERRIDES =. "${@['', 'zx3-module:']['zx3-module' != '${MACHINE}']}"

require conf/machine/zynq-override.inc

PACKAGE_EXTRA_ARCHS:append = "${@['', ' zx3_module']['zx3-module' != "${MACHINE}"]}"
