MACHINEOVERRIDES =. "${@['', 'zx5-module:']['zx5-module' != '${MACHINE}']}"

require conf/machine/zynq-generic.conf

PACKAGE_EXTRA_ARCHS:append = "${@['', ' zx5_module']['zx5-module' != "${MACHINE}"]}"
